### PR TITLE
Add `cte_name` option in the `test` macro

### PR DESCRIPTION
**Pull request by billwallis**
## Summary (feature request)
Add the option `cte_name` to the `test` macro which will return the results of the given CTE from the model's SQL, rather than the final results of the model

This is implemented by creating a new macro, [`select_from_cte`](https://github.com/Bilbottom/dbt-unit-testing/blob/3ac340a302b75c2a168129b5bb4851a522c19832/macros/sql_builders.sql#L106-L128), which is explicitly called in the `build_model_complete_sql` macro (all inside the [`sql_builders.sql`](https://github.com/EqualExperts/dbt-unit-testing/blob/master/macros/sql_builders.sql) file)

## Why?
Most dbt models will have some ["logical" CTEs](https://github.com/dbt-labs/corp/blob/725b6e9cf2af208d24a52fc04095c2feaff20b9d/dbt_style_guide.md?plain=1#L147-L151) that do some work before the final select statement

Without extracting these CTEs into their own models, we can't write a unit test to validate that the CTE itself is doing what we intend it to do -- this change would add this feature

## Requirements (of the user)
The implementation assumes that the users follow [the dbt-labs style guide](https://github.com/dbt-labs/corp/blob/main/dbt_style_guide.md) and [end their model with the `select * from final` line](https://github.com/dbt-labs/corp/blob/725b6e9cf2af208d24a52fc04095c2feaff20b9d/dbt_style_guide.md?plain=1#L157-L158) (the implementation just replaces the `select * from final` with `select * from {{ cte_name }}`)

To use the `cte_name` argument, the user needs to provide it in the `options` dictionary in the `test` call:
```jinja
{% call dbt_unit_testing.test(
    "dummy_model",
    "A CTE unit test",
    {"cte_name": "some_cte_in_the_model"}
) %}
    ...
{% endcall %}
```

(The following clarification is adjusted from [a comment below](https://github.com/EqualExperts/dbt-unit-testing/pull/134#issuecomment-1514682442))
To clarify, this doesn't break the existing behaviour of the `test` macro and ignoring the `cte_name` option will run the `test` macro as normal. It's only when the `cte_name` option is used that the `select * from final` pattern would (currently) be required, so existing users of this package can safely continue to use their own style guides for unit testing (they just won't be able to use this option)

### Some Error Handling
If the `select * from final` text can't be found, then the following compile error is raised:
```
Compilation Error in test  <test name and path>
   Unable to find `select * from final` in the model SQL
```
The pattern matching is quite forgiving -- Python's `re` module is used to do a case-insensitive and space-insensitive replacement

If the CTE name can't be found, the usual database error will be thrown instead

## Worked Example
Consider the following dummy model, `dummy_model`:
```sql
WITH

SRC_MODEL AS (
    SELECT *
    FROM {{ ref("some_model") }}
),

CTE_1 AS (
    SELECT 1 AS ID
),
CTE_2 AS (
    SELECT 2 AS ID
),

FINAL AS (
    SELECT SUM(ID) AS ID
    FROM (
              SELECT ID FROM CTE_1
        UNION SELECT ID FROM CTE_2
        UNION SELECT ID FROM SRC_MODEL
    )
)

SELECT * FROM FINAL
```

With this model in mind, we can put together tests that can mock the results of the different CTEs:

cte-name-unit-tests

The tests above test the output (the `FINAL` CTE) like normal when no `cte_name` is provided, plus each of the other 'building-block' CTEs when the `cte_name` is provided

In practice, I'd avoid the tests on the ["import" CTEs](https://github.com/dbt-labs/corp/blob/725b6e9cf2af208d24a52fc04095c2feaff20b9d/dbt_style_guide.md?plain=1#L147-L151) and would give the tests better names that reference the model that they're testing

## Tests
I haven't added any since I'm not really too sure where to fit them in -- if you can point me in the right direction, I can throw some in

## Changes
For clarity, I've only changed 2 files:
* [`macros/sql_builders.sql`](https://github.com/EqualExperts/dbt-unit-testing/blob/master/macros/sql_builders.sql)
* [`README.md`](https://github.com/EqualExperts/dbt-unit-testing/blob/master/README.md)

### CODE REVIEW

**Comment by cdiniz** [comment]
Hi @Bilbottom,

Thank you for your contribution and well-articulated pull request.

We appreciate the effort you put into basing your approach on the dbt labs style guide, although we have encountered several projects that have their own style guides. We aim to keep the framework as flexible as possible to accommodate different styling preferences.

Furthermore, we would like to highlight that our framework supports ephemeral models, which can be useful when dealing with complex common table expressions (CTEs) and when testing different parts of the final model. This feature enhances the testability and simplifies the complexity of the models.

Thank you again for your input and collaboration. However, we have decided not to proceed with your suggestion as our existing features, such as ephemeral models, can effectively address the issues you raised.

**Comment by Bilbottom** [comment]
> Hi @Bilbottom,
> 
> Thank you for your contribution and well-articulated pull request.
> 
> We appreciate the effort you put into basing your approach on the dbt labs style guide, although we have encountered several projects that have their own style guides. We aim to keep the framework as flexible as possible to accommodate different styling preferences.
> 
> Furthermore, we would like to highlight that our framework supports ephemeral models, which can be useful when dealing with complex common table expressions (CTEs) and when testing different parts of the final model. This feature enhances the testability and simplifies the complexity of the models.
> 
> Thank you again for your input and collaboration. However, we have decided not to proceed with your suggestion as our existing features, such as ephemeral models, can effectively address the issues you raised.

Thanks for coming back so quickly, @cdiniz! 😄 

I understand your reasons for the rejection

The use of ephemeral models is actually what I'm trying to avoid by introducing this feature -- I have friends that work with projects that have used that approach (making all logical CTEs ephemeral), and their experience is that it unhelpfully inflates the number of models in the projects and makes the projects harder to understand

I totally agree with the point about different style guides though, and I was expecting to get this response 😋 I'll have a think about alternative implementations

If I can find an approach that doesn't require the use of the `select * from final` line, would you re-consider this PR? (I won't try if the answer is "no" 😝)

**Comment by cdiniz** [comment]
Thank you all for your feedback. @gnilrets, I agree with your point that private methods are implementation details and should not be tested directly. As you mentioned, we should focus on testing the public interface and its behaviour, and the effects of private 'methods' on the interface.

However, we are open to considering different perspectives and feedback. If you have any further thoughts or suggestions on this matter, please let us know. Thank you again for your input.

**Comment by darkdreamingdan** [comment]
hello, my team are converting our jobs over from DBT to python - we love this library because of the ability to transfer our unit tests.  However, within python we get much more autonomy to take decisions over the granularity of our testing - soemtimes we want to be able to thoroughly interrogate individual functions (at the expense of time to refactor if implementation changes).

it's my belief that the engineer should be empowered to take that call, rather than the language enforcing it.  it would be strange for a typical language to prevent people from testing individual functions if they choose.  If we apply that here, i would be highly supportive of having a mechanism to also test our individual CTEs so long as it does not break backwards compatibility.

**Comment by Will-Gaines** [comment]
I am inclined to agree with @darkdreamingdan
If this new feature doesn't break backwards compatibility, tests that don't use this flag, or models that aren't using the dbt-labs style guide, is it really such a problem for the far greater testability and flexibility the feature can bring? You give engineers far more power to test each step of their models at the cost of ~30 characters per model. And in some sense it is less restrictive - currently a logic block has to be an ephemeral model of it's own to be tested, while this feature would give developers more choice in how they want to build their models, without sacrificing testability

And personally, I don't see that having a (very small) style convention being a requirement for using a certain feature is that restrictive. Certainly to my mind it's no less restrictive than for example `pytest` requiring files and functions to be named in certain ways?

**Comment by NiallRees** [comment]
Can we get this merged? The complexity of the typical model means the unit of testing is massive. It feels like the equivalent of being able to test an entire python module (model) vs each individual method (CTE). It makes writing test cases more complicated, and resolving issues.

**Pull request closed without merging**
